api = "0.5"

[buildpack]
  id = "paketo-buildpacks/cpython"
  name = "Paketo CPython Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.8.x"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.6.14:*:*:*:*:*:*:*"
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    licenses = ["CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.6.14?checksum=70064897bc434d6eae8bcc3e5678f282b5ea776d60e695da548a1219ccfd27a5&download_url=https://www.python.org/ftp/python/3.6.14/Python-3.6.14.tgz"
    sha256 = "42bc2ff367720102e8c3bf6ace78c52fdb2238a833975ec348a9fbcdd94a6844"
    source = "https://www.python.org/ftp/python/3.6.14/Python-3.6.14.tgz"
    source_sha256 = "70064897bc434d6eae8bcc3e5678f282b5ea776d60e695da548a1219ccfd27a5"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.6.14_linux_x64_bionic_42bc2ff3.tgz"
    version = "3.6.14"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.6.15:*:*:*:*:*:*:*"
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    licenses = ["CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.6.15?checksum=54570b7e339e2cfd72b29c7e2fdb47c0b7b18b7412e61de5b463fc087c13b043&download_url=https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz"
    sha256 = "92d8cbc07d8923469d9a6527f0e61e32c6a47b7dbc053c6e96cb4b8902321fdd"
    source = "https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz"
    source_sha256 = "54570b7e339e2cfd72b29c7e2fdb47c0b7b18b7412e61de5b463fc087c13b043"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.6.15_linux_x64_bionic_92d8cbc0.tgz"
    version = "3.6.15"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.7.11:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    licenses = ["CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.7.11?checksum=b4fba32182e16485d0a6022ba83c9251e6a1c14676ec243a9a07d3722cd4661a&download_url=https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz"
    sha256 = "031820f81b6a1a471bef86e83ec6f9e50d9dd2624cbf811fb76e6ca11a30a3a0"
    source = "https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz"
    source_sha256 = "b4fba32182e16485d0a6022ba83c9251e6a1c14676ec243a9a07d3722cd4661a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.7.11_linux_x64_bionic_031820f8.tgz"
    version = "3.7.11"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.7.12:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    licenses = ["CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.7.12?checksum=33b4daaf831be19219659466d12645f87ecec6eb21d4d9f9711018a7b66cce46&download_url=https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz"
    sha256 = "9126994d0d80d4f301f5bdedc4faf06450d7df28b6c6f42f4d00442549fb0f11"
    source = "https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz"
    source_sha256 = "33b4daaf831be19219659466d12645f87ecec6eb21d4d9f9711018a7b66cce46"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.7.12_linux_x64_bionic_9126994d.tgz"
    version = "3.7.12"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.8.11:*:*:*:*:*:*:*"
    deprecation_date = "2024-10-01T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.8.11?checksum=b77464ea80cec14581b86aeb7fb2ff02830e0abc7bcdc752b7b4bdfcd8f3e393&download_url=https://www.python.org/ftp/python/3.8.11/Python-3.8.11.tgz"
    sha256 = "ea3048f0f8bcf87b2fb9ebd3be78351f924c5d72b0d199f1550965114c9ac921"
    source = "https://www.python.org/ftp/python/3.8.11/Python-3.8.11.tgz"
    source_sha256 = "b77464ea80cec14581b86aeb7fb2ff02830e0abc7bcdc752b7b4bdfcd8f3e393"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.8.11_linux_x64_bionic_ea3048f0.tgz"
    version = "3.8.11"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.8.12:*:*:*:*:*:*:*"
    deprecation_date = "2024-10-01T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.8.12?checksum=316aa33f3b7707d041e73f246efedb297a70898c4b91f127f66dc8d80c596f1a&download_url=https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz"
    sha256 = "0ba8caf6faac53286732448a1c799073bcc57be5925faab157bbccddc87c3c2e"
    source = "https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz"
    source_sha256 = "316aa33f3b7707d041e73f246efedb297a70898c4b91f127f66dc8d80c596f1a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.8.12_linux_x64_bionic_0ba8caf6.tgz"
    version = "3.8.12"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.9.7:*:*:*:*:*:*:*"
    deprecation_date = "2025-10-01T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.9.7?checksum=a838d3f9360d157040142b715db34f0218e535333696a5569dc6f854604eb9d1&download_url=https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz"
    sha256 = "6bb3531a673f271167eef25ca77f1d2b0d7e96664ac3730d3bf35a059424ea73"
    source = "https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz"
    source_sha256 = "a838d3f9360d157040142b715db34f0218e535333696a5569dc6f854604eb9d1"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.9.7_linux_x64_bionic_6bb3531a.tgz"
    version = "3.9.7"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:python:python:3.9.8:*:*:*:*:*:*:*"
    deprecation_date = "2025-10-01T00:00:00Z"
    id = "python"
    licenses = ["0BSD", "CNRI-Python-GPL-Compatible"]
    name = "Python"
    purl = "pkg:generic/python@3.9.8?checksum=7447fb8bb270942d620dd24faa7814b1383b61fa99029a240025fd81c1db8283&download_url=https://www.python.org/ftp/python/3.9.8/Python-3.9.8.tgz"
    sha256 = "e652adbd53ea7df08c4ecad7626b6a1b40b0e381fdb99144d7760e23709cbeda"
    source = "https://www.python.org/ftp/python/3.9.8/Python-3.9.8.tgz"
    source_sha256 = "7447fb8bb270942d620dd24faa7814b1383b61fa99029a240025fd81c1db8283"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/python/python_3.9.8_linux_x64_bionic_e652adbd.tgz"
    version = "3.9.8"

  [[metadata.dependency-constraints]]
    constraint = "3.6.*"
    id = "python"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.7.*"
    id = "python"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.8.*"
    id = "python"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.9.*"
    id = "python"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
