api = "0.5"

[buildpack]
  id = "paketo-buildpacks/cpython"
  name = "Paketo CPython Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    python = "3.8.x"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "44f5e786c1b14aa14241f0c2630b1e893fba9a02be45116560ad6c5f69a645d9"
    source = "https://www.python.org/ftp/python/3.6.14/Python-3.6.14.tgz"
    source_sha256 = "70064897bc434d6eae8bcc3e5678f282b5ea776d60e695da548a1219ccfd27a5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.6.14_linux_x64_cflinuxfs3_44f5e786.tgz"
    version = "3.6.14"

  [[metadata.dependencies]]
    deprecation_date = "2021-12-23T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "00084a8adf71242adb222e41dc5d41b8fe0b25f250c77d750b4f7c2e95d81e03"
    source = "https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz"
    source_sha256 = "54570b7e339e2cfd72b29c7e2fdb47c0b7b18b7412e61de5b463fc087c13b043"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.6.15_linux_x64_cflinuxfs3_00084a8a.tgz"
    version = "3.6.15"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "b214c524e0d5c32c41d1bbf3c766eb00b8c55e7da00ad9e309e158624c025573"
    source = "https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz"
    source_sha256 = "b4fba32182e16485d0a6022ba83c9251e6a1c14676ec243a9a07d3722cd4661a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.7.11_linux_x64_cflinuxfs3_b214c524.tgz"
    version = "3.7.11"

  [[metadata.dependencies]]
    deprecation_date = "2023-06-27T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "b89d366ceea58c4eec39bf20b7d3899fe72b9ef2b8debc6ac79d5810180ecba7"
    source = "https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz"
    source_sha256 = "33b4daaf831be19219659466d12645f87ecec6eb21d4d9f9711018a7b66cce46"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.7.12_linux_x64_cflinuxfs3_b89d366c.tgz"
    version = "3.7.12"

  [[metadata.dependencies]]
    deprecation_date = "2024-10-14T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "e57abfeaf404776ba79b100949dbbf4d3db069d691b6db5d84a8d2d192ff43f3"
    source = "https://www.python.org/ftp/python/3.8.11/Python-3.8.11.tgz"
    source_sha256 = "b77464ea80cec14581b86aeb7fb2ff02830e0abc7bcdc752b7b4bdfcd8f3e393"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.8.11_linux_x64_cflinuxfs3_e57abfea.tgz"
    version = "3.8.11"

  [[metadata.dependencies]]
    deprecation_date = "2024-10-14T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "63d8339a7a74a1f97bc8758076818607cc36cb39d65f676268d996b9c3eb0235"
    source = "https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz"
    source_sha256 = "316aa33f3b7707d041e73f246efedb297a70898c4b91f127f66dc8d80c596f1a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.8.12_linux_x64_cflinuxfs3_63d8339a.tgz"
    version = "3.8.12"

  [[metadata.dependencies]]
    deprecation_date = "2025-10-05T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "caec8bfab1a06a2922bbc0c76076b5df70d6766e44df65ee03b17012aa436434"
    source = "https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz"
    source_sha256 = "d0a35182e19e416fc8eae25a3dcd4d02d4997333e4ad1f2eee6010aadc3fe866"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.9.6_linux_x64_cflinuxfs3_caec8bfa.tgz"
    version = "3.9.6"

  [[metadata.dependencies]]
    deprecation_date = "2025-10-05T00:00:00Z"
    id = "python"
    name = "Python"
    sha256 = "eacb311da9967809baba9315b13319cf7fc742f1f9edf94e39fe95ae9784eca7"
    source = "https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz"
    source_sha256 = "a838d3f9360d157040142b715db34f0218e535333696a5569dc6f854604eb9d1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "http://dash-app-resources.plotly-system.svc.cluster.local/packages/kpack-offline-files/python_3.9.7_linux_x64_cflinuxfs3_eacb311d.tgz"
    version = "3.9.7"

  [[metadata.dependency_deprecation_dates]]
    date = "2021-12-23T00:00:00Z"
    link = "https://www.python.org/dev/peps/pep-0494/"
    name = "Python"
    version_line = "3.6.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2023-06-27T00:00:00Z"
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.7.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2023-06-27T00:00:00Z"
    link = "https://www.python.org/dev/peps/pep-0537/"
    name = "Python"
    version_line = "3.8.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
